---
- name: Update all server
  hosts: all
  become: yes
  tasks:
  - name: update the webpage
    copy:
      src: static.html
      dest: /var/www/html/static.html
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 

  - name: update the webpage
    copy:
      src: static.html
      dest: /var/www/html/static.html
    when: ansible_distribution ==  "Ubuntu"



...
