---
- name: Update all server
  hosts: all
  become: yes
  tasks:
  - name: update the webpage
    copy:
      src: date.j2
      dest: /var/www/html/date.php
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 

  - name: update the webpage
    copy:
      src: date.j2
      dest: /var/www/html/date.php
    when: ansible_distribution ==  "Ubuntu"

  - name: install php
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: install php
    apt:
      name: php
      state: present
    when: ansible_distribution ==  "Ubuntu"

  - name: restart httpd 
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: restart httpd
    service:
      name: apache2
      state: restarted
    when: ansible_distribution ==  "Ubuntu"












...
