---
  - name: restart httpd 
    service:
      name: httpd
      state: restarted
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

 
  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: ansible_distribution ==  "Ubuntu"

...
