---

  - name: update the webpage
    copy:
      src: static.html
      dest: /var/www/html/static.html
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 

  - name: update the webpage
    copy:
      src: static.html
      dest: /var/www/html/static.html
    when: ansible_distribution ==  "Ubuntu"


  - name: update the webpage
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    -  restart httpd
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 
   
  - name: update the webpage
    template:
      src: ports.j2
      dest: /etc/apache2/ports.conf
    notify:
    -  restart apache2
    when: ansible_distribution ==  "Ubuntu"
  
  - name: install php
    yum:
      name: php
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: install php
    apt:
      name: php
      state: present
    when: ansible_distribution ==  "Ubuntu"
  

...
